$message = '<html>';
$message .= '<head>';
$message .= '<meta charset="UTF-8">';
$message .= '<meta name="viewport" content="width=device-width, initial-scale=1">';
$message .= '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">';

$message .= '</head>';
$message .= '<body style="font-family: Arial; margin: 0;">';

$message .= '<div style="padding: 2px; text-align: center; background: #000000; color: #ff9900; font-size: 20px;">';
 $message .= '<h1>BIT<font color="#999999">MAX</font> </h1>';
 $message .= '<p>YOUR REGISTRATION WAS SUCCESSFUL!</p>';
$message .= '</div>';

$message .= '<div style="padding:60px;" align="center">';
$message .= '<h1>Welcome '.$this->first_name.'</h1>';
$message .= '<p>Thanks for joining Bittrada. Bittrada.com is the place to go for an outstanding crypto success.
</p>';
$message .= '<p>At Bittrada we believe everyone deserve to make financial gains trading and investing in bitcoin and other cryptocurrencies.</p>';
$message .= '<p>There are over 200 million people in the world with crypto access but no knowledge on how to be successful in the cryptocurrency business. Our mission is to give the opportunity for anyone willing to grab this financial opportunity presented by bitcoin and cryptocurrencies. You can <a href="https://bittrada.com/login.php#content" target="_blank">invest</a> and earn amazing profits generated by our miners and traders.  </p>';
$message .= '<p>Thanks, and again, welcome aboard.</p>';
$message .= '<p><font color="black"><b> Team Bittrada</b></font></p>';
$message .= '</div>';


$message .= '<div style="padding: 1px; left: 0; bottom: 0; background: #000000; color: #ff9900; text-align: center;">';

$message .= '<p>';
$message .= '<a href="#"><img src="https://thekayword.files.wordpress.com/2011/07/facebook-icon-black-background.jpg?w=240" alt="" style="width:30px;height:20px;"></a>  ';
$message .= '<a href="#"><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0gJ6BwHNprnG7ZuoH3k2K0xVKcNIqnMtyfw&usqp=CAU" alt="" style="width:30px;height:20px;"></a> ';
$message .= '<a href="#"><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRNTKD7JU_vWA-kxMIX6RQPE0xDiUILf5UcQ&usqp=CAU" alt="" style="width:30px;height:20px;"></a> ';
$message .= '<a href="#"><img src="https://wallpapercave.com/wp/wp7702506.jpg" alt="" style="width:30px;height:20px;"></a> ';
$message .= '<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQufL8QCGUCMh208v3lsWZilwbdXr1aJQBpJQ&usqp=CAU" alt="" style="width:30px;height:20px;"> +888-888-8888 ';
$message .= 'Copyright | '.date('Y').' | ';
$message .=  '<a href="#" target="_blank">Bittrada.com</a>';
$message .= '</p>';
$message .= '</div>';

$message .= '</body>';
$message .= '</html>';
