<?php
include ('../../encryptdecrypt.php');

class RegisterClass{

private $email = "";
private $phone = "";
private $first_name = "";
private $last_name = "";
private $passwd = "";
private $referral_id = "";
private $country = "";

public function __construct($phone,$first_name,$last_name,$email,$passwd,$referral_id,$country){

$this->email = $email;
$this->phone = $phone;
$this->first_name = $first_name;
$this->last_name = $last_name;
$this->passwd = $passwd;
$this->referral_id = $referral_id;
$this->country = $country;

}


function sendWelcomeSms(){

//add recipient email
$to = $this->email;

//create Subject
$subject = "Your registration was successful";


//set the mail headers
$headers = "MIME-Version: 1.0\r\n";
$headers .= "Content-type: text/html; charset=ISO-8859-1\r\n";
$headers .= "From: Bittrada <noreply@Bittrada.com>\r\n";
$headers .= "X-Priority: 1\r\n";
$headers .= "X-MSMail-Priority: High\r\n\r\n";

//constrcut message
$message = '<html>';
$message .= '<head>';
$message .= '<meta charset="UTF-8">';
$message .= '<meta name="viewport" content="width=device-width, initial-scale=1">';
$message .= '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">';

$message .= '</head>';
$message .= '<body style="font-family: Arial; margin: 0;">';

$message .= '<div style="padding: 2px; text-align: center; background: #1a0d00; color: #ff8000; font-size: 20px;">';
 $message .= '<h1>B<font color="#ffffff">ITTRADA</font> </h1>';
 $message .= '<p>YOUR REGISTRATION WAS SUCCESSFUL!</p>';
$message .= '</div>';

$message .= '<div style="padding:60px;" align="center">';
$message .= '<h1>Welcome '.$this->first_name.'</h1>';
$message .= '<p>Thanks for joining Bittrada. Bittrada.com is the place to go for an outstanding crypto success.
</p>';
$message .= '<p>At Bittrada we believe everyone deserve to make financial gains, trading and investing in bitcoin and other cryptocurrencies.</p>';
$message .= '<p>There are over 200 million people in the world with crypto access but no knowledge on how to be successful in the cryptocurrency business. Our mission is to give the opportunity for anyone willing to grab this financial opportunity presented by bitcoin and cryptocurrencies. You can <a href="https://www.bittrada.com/template/login.php" target="_blank">invest</a> and earn amazing profits generated by our miners and traders.  </p>';
$message .= '<p>Thanks, and again, welcome aboard.</p>';
$message .= '<p><font color="black"><b> Team Bittrada</b></font></p>';
$message .= '</div>';


$message .= '<div style="padding: 1px; left: 0; bottom: 0; background: #1a0d00; color: #ff8000; text-align: center;">';

$message .= '<p>';
$message .= '<a href="#"><img src="https://thekayword.files.wordpress.com/2011/07/facebook-icon-black-background.jpg?w=240" alt="" style="width:30px;height:20px;"></a>  ';
$message .= '<a href="#"><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0gJ6BwHNprnG7ZuoH3k2K0xVKcNIqnMtyfw&usqp=CAU" alt="" style="width:30px;height:20px;"></a> ';
$message .= '<a href="#"><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRNTKD7JU_vWA-kxMIX6RQPE0xDiUILf5UcQ&usqp=CAU" alt="" style="width:30px;height:20px;"></a> ';
$message .= '<a href="#"><img src="https://wallpapercave.com/wp/wp7702506.jpg" alt="" style="width:30px;height:20px;"></a> ';
$message .= '<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQufL8QCGUCMh208v3lsWZilwbdXr1aJQBpJQ&usqp=CAU" alt="" style="width:30px;height:20px;"> +888-888-8888 ';
$message .= 'Copyright | '.date('Y').' | ';
$message .=  '<a href="https://www.bittrada.com" target="_blank">Bittrada.com</a>';
$message .= '</p>';
$message .= '</div>';

$message .= '</body>';
$message .= '</html>';

$message = wordwrap($message, 72);


//send mail
mail($to, $subject, $message, $headers);

return array("status"=>"true","message"=>"Registered successfully!");
}
//end of sendWelcomeSms



//start of  function insertWalletAndTransactionDefacult.
function insertWalletAndTransactionDefault(){
include ('../../db.php');
$client_id = "---";
$btc = "---";
$eth = "---";
$bch = "---";
$usdt = "---";
$zero_roi = "0";
$ledger_bal = "0";
$act_bal = "0";
$trans_amt = "0";
$status = "---";
$plan = "---";

//inserting default values into wallet
$sql = "SELECT * FROM wallet WHERE investor_email = '$this->email'";
$result = $conn->query($sql);
if ($result->num_rows == 0 ){

//inserting into wallet
  $sql = "INSERT INTO wallet (investor_id, investor_email, btc_address, eth_address, bch_address, usdt_address, plan, ledger_bal, available_bal, act_bal)
VALUES ('$client_id', '$this->email', '$btc', '$eth', '$bch', '$usdt', '$plan', '$ledger_bal', '$zero_roi', '$act_bal')";

//checking if inserting wallet is successful
if ($conn->query($sql) === TRUE) {
  
//inserting into transactions  
$sql = "INSERT INTO transactions (client_id, client_email, amount, status)
VALUES ('$client_id', '$this->email', '$ledger_bal', '$status')";

//checking if transactions details is updated successfully
if ($conn->query($sql) === TRUE){

//response if inserting transaction details successful
	return $this->sendWelcomeSms();

}else{

return array("status"=>false,"message"=>"Registration Incomplete!!");	
}
}else{
	return array("status"=>false,"message"=>"Registration Incomplete!!!");
}

}else{

return array("status"=>false,"message"=>"Registration Incomplete!");

}


}
//end of funcstion insertWalletAndTransactionDefacult




function checkUser(){

include ('../../db.php');
$passkey = "firstfullsite";
$encryptDecrypt = new EncryptDecrypt($this->passwd);
$encryptedpass = $encryptDecrypt->encrypt($this->passwd, $passkey);

$sql = "SELECT * FROM register WHERE email = '$this->email'";
$result = $conn->query($sql);
if ($result->num_rows > 0 ) {

return array("status"=>false,"message"=>"This User exists");
}else{

	$sql = "INSERT INTO register (first_name, last_name, email, password, phone, referral_id, country)
VALUES ('$this->first_name', '$this->last_name', '$this->email', '$encryptedpass', '$this->phone', '$this->referral_id', '$this->country')";


if ($conn->query($sql) === TRUE) {
    
    return $this->insertWalletAndTransactionDefault();

}else{
	return array("status"=>false,"message"=>"Registration failed");
}


}

//end of function checkUser and registeration successful.



}
}
?>